#!/bin/sh
this=$(readlink -f ${0})
here=$(readlink -f $(dirname ${this}))

die() { echo $@; exit 1; }

cd ${here}/.. &&
    v=$(git tag | sort -Vr | head -1) &&
    docker build -t "popcorn:${v}" . &&
    docker images | grep "${v}"
