#!/bin/sh
this=$(readlink -f ${0})
here=$(readlink -f $(dirname ${this}))

die() { echo $@; exit 1; }

cd ${here}/..
rdir="../popcornrelease"
[ -d ${rdir} ] || die "${rdir} not found"

version=$(git tag | sort -V | tail -1)
echo "creating release version ${version}"
git checkout ${version} || die failed checkout ${version}
(cd doc; pdflatex ../srcdoc/popcorn-manual.tex ) || echo Manual generation failed
git archive --output=${rdir}/popcorn-${version}.tar.gz --prefix=popcorn/ ${version} js doc bin
ls -lt ${rdir} | head -2

